# Generated by Django 2.1.7 on 2019-03-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('slack_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('name', models.CharField(max_length=60)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('name', models.CharField(max_length=60)),
                ('selected_branch', models.IntegerField(blank=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, null=True, to='app.Branches')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('name', models.CharField(max_length=60)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Repositories')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.AddField(
            model_name='projects',
            name='repositories',
            field=models.ManyToManyField(blank=True, null=True, to='app.Repositories'),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Teams'),
        ),
    ]
